/**
 * generated by Xtext
 */
package org.processus.ecleek.ui.contentassist;

import org.processus.ecleek.ui.contentassist.AbstractLeekProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class LeekProposalProvider extends AbstractLeekProposalProvider {
}
