/**
 * generated by Xtext
 */
package org.processus.ecleek.validation;

import org.processus.ecleek.validation.AbstractLeekValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class LeekValidator extends AbstractLeekValidator {
}
