package org.processus.leekwars;

public enum Chip {
	CHIP_ADRENALINE, CHIP_ARMOR, CHIP_ARMORING, CHIP_BANDAGE, CHIP_CURE, CHIP_DOPING, CHIP_DRIP, CHIP_FLAME, CHIP_FLASH, CHIP_FORTRESS, CHIP_HELMET, CHIP_ICE, CHIP_ICEBERG, CHIP_INVERSION, CHIP_LEATHER_BOOTS, CHIP_LIBERATION, CHIP_LIGHTNING, CHIP_METEORITE, CHIP_MOTIVATION, CHIP_PEBBLE, CHIP_PROTEIN, CHIP_RAGE, CHIP_RAMPART, CHIP_REFLEXES, CHIP_RESURRECTION, CHIP_ROCK, CHIP_ROCKFALL, CHIP_SEVEN_LEAGUE_BOOTS, CHIP_SHIELD, CHIP_SHOCK, CHIP_SPARK, CHIP_STALACTITE, CHIP_STEROID, CHIP_STRETCHING, CHIP_TELEPORTATION, CHIP_VACCINE, CHIP_WALL, CHIP_WARM_UP, CHIP_WINGED_BOOTS
}
