package org.processus.leekwars;

public enum Weapon {
	WEAPON_B_LASER, WEAPON_DESTROYER, WEAPON_DOUBLE_GUN, WEAPON_ELECTRISOR, WEAPON_FLAME_THROWER, WEAPON_GAZOR, WEAPON_GRENADE_LAUNCHER, WEAPON_LASER, WEAPON_MACHINE_GUN, WEAPON_MAGNUM, WEAPON_M_LASER, WEAPON_PISTOL, WEAPON_SHOTGUN

}
