/*
 * generated by Xtext
 */
package org.processus.ecleek.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LeekUiModule extends org.processus.ecleek.ui.AbstractLeekUiModule {
	public LeekUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
        return LeekEObjectDocumentationProvider.class;
    }
}
