/*
* generated by Xtext
*/
package org.processus.ecleek;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LeekUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.processus.ecleek.ui.internal.LeekActivator.getInstance().getInjector("org.processus.ecleek.Leek");
	}
	
}
