/*
 * generated by Xtext
 */
package org.processus.ecleek.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLeekValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.processus.ecleek.leek.LeekPackage.eINSTANCE);
		return result;
	}
}
