/*
* generated by Xtext
*/
package org.processus.ecleek;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LeekStandaloneSetup extends LeekStandaloneSetupGenerated{

	public static void doSetup() {
		new LeekStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

