/*
 * generated by Xtext
 */
package org.processus.ecleek;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LeekRuntimeModule extends org.processus.ecleek.AbstractLeekRuntimeModule {

}
