/*
* generated by Xtext
*/
package org.processus.ecleek.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.processus.ecleek.services.LeekGrammarAccess;

public class LeekParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LeekGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.processus.ecleek.parser.antlr.internal.InternalLeekParser createParser(XtextTokenStream stream) {
		return new org.processus.ecleek.parser.antlr.internal.InternalLeekParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}
	
	public LeekGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LeekGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
